var result = {
    "header": {
      "returnCode": 0,
      "returnDesc": "OK"
    },
    "body": {
      "BoardList": [
        {
          "boardId": "INITBD000001",
          "hasChildren": "0",
          "boardName": "전사게시판",
          "boardParentId": "root",
          "siblingOrder": "1",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000056851",
          "hasChildren": "3",
          "boardName": "업무 공지",
          "boardParentId": "root",
          "siblingOrder": "6",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "0",
          "categoryList": ""
        },
        {
          "boardId": "120000043472",
          "hasChildren": "0",
          "boardName": "교육 훈련 공지",
          "boardParentId": "120000056851",
          "siblingOrder": "0",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000056855",
          "hasChildren": "0",
          "boardName": "일일 포인트 공지",
          "boardParentId": "120000056851",
          "siblingOrder": "1",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000056862",
          "hasChildren": "0",
          "boardName": "개통 현황 공지",
          "boardParentId": "120000056851",
          "siblingOrder": "2",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000032964",
          "hasChildren": "4",
          "boardName": "업무별 매뉴얼",
          "boardParentId": "root",
          "siblingOrder": "7",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "0",
          "categoryList": ""
        },
        {
          "boardId": "120000032378",
          "hasChildren": "0",
          "boardName": "그룹웨어 매뉴얼",
          "boardParentId": "120000032964",
          "siblingOrder": "0",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000032967",
          "hasChildren": "0",
          "boardName": "HR 매뉴얼",
          "boardParentId": "120000032964",
          "siblingOrder": "1",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000032972",
          "hasChildren": "0",
          "boardName": "재무 매뉴얼",
          "boardParentId": "120000032964",
          "siblingOrder": "2",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000033229",
          "hasChildren": "0",
          "boardName": "모바일 메뉴얼",
          "boardParentId": "120000032964",
          "siblingOrder": "3",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000072769",
          "hasChildren": "4",
          "boardName": "경조/행사",
          "boardParentId": "root",
          "siblingOrder": "9",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "0",
          "categoryList": ""
        },
        {
          "boardId": "120000072781",
          "hasChildren": "0",
          "boardName": "경사",
          "boardParentId": "120000072769",
          "siblingOrder": "0",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000072791",
          "hasChildren": "0",
          "boardName": "조사",
          "boardParentId": "120000072769",
          "siblingOrder": "1",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000152646",
          "hasChildren": "0",
          "boardName": "생일파티",
          "boardParentId": "120000072769",
          "siblingOrder": "2",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000152678",
          "hasChildren": "0",
          "boardName": "식구DAY",
          "boardParentId": "120000072769",
          "siblingOrder": "3",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000057356",
          "hasChildren": "8",
          "boardName": "인사 Q&A",
          "boardParentId": "root",
          "siblingOrder": "10",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "0",
          "categoryList": ""
        },
        {
          "boardId": "120000086215",
          "hasChildren": "0",
          "boardName": "급여",
          "boardParentId": "120000057356",
          "siblingOrder": "1",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": "3월,4월,5월,6월,7월,8월,9월,10월,11월,12월"
        },
        {
          "boardId": "120000057367",
          "hasChildren": "0",
          "boardName": "복리후생",
          "boardParentId": "120000057356",
          "siblingOrder": "2",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000131715",
          "hasChildren": "0",
          "boardName": "연차",
          "boardParentId": "120000057356",
          "siblingOrder": "7",
          "boardLevel": "2",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000034467",
          "hasChildren": "0",
          "boardName": "양식함",
          "boardParentId": "root",
          "siblingOrder": "11",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000031815",
          "hasChildren": "0",
          "boardName": "FAQ",
          "boardParentId": "root",
          "siblingOrder": "12",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "0",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        },
        {
          "boardId": "120000032583",
          "hasChildren": "0",
          "boardName": "묻고 답하기",
          "boardParentId": "root",
          "siblingOrder": "13",
          "boardLevel": "1",
          "boardRootId": "0",
          "writePermit": "1",
          "isReply": "1",
          "isComment": "1",
          "isBoard": "1",
          "categoryList": ""
        }
      ]
    }
  }